version: '2'

services:

  orderer.securehealth.com:
    container_name: orderer.securehealth.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/gopath/fabric/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/opt/gopath/fabric/channel-artifacts/genesis.block
    - ../config/crypto-config/ordererOrganizations/securehealth.com/orderers/orderer.securehealth.com/msp:/var/hyperledger/orderer/msp
    - ../config/crypto-config/ordererOrganizations/securehealth.com/orderers/orderer.securehealth.com/tls/:/var/hyperledger/orderer/tls
    - orderer.securehealth.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.rabat.securehealth.com:
    container_name: peer0.rabat.securehealth.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=peer0.rabat.securehealth.com
      - CORE_PEER_ADDRESS=peer0.rabat.securehealth.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.rabat.securehealth.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.rabat.securehealth.com:7051
      - CORE_PEER_LOCALMSPID=HospitalRabatMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../config/crypto-config/peerOrganizations/rabat.securehealth.com/peers/peer0.rabat.securehealth.com/msp:/etc/hyperledger/fabric/msp
        - ../config/crypto-config/peerOrganizations/rabat.securehealth.com/peers/peer0.rabat.securehealth.com/tls:/etc/hyperledger/fabric/tls
        - peer0.rabat.securehealth.com:/var/hyperledger/production
    ports:
      - 7051:7051
  

  peer0.casa.securehealth.com:
    container_name: peer0.casa.securehealth.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=peer0.casa.securehealth.com
      - CORE_PEER_ADDRESS=peer0.casa.securehealth.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.casa.securehealth.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.casa.securehealth.com:7051
      - CORE_PEER_LOCALMSPID=HospitalCasaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../config/crypto-config/peerOrganizations/casa.securehealth.com/peers/peer0.casa.securehealth.com/msp:/etc/hyperledger/fabric/msp
        - ../config/crypto-config/peerOrganizations/casa.securehealth.com/peers/peer0.casa.securehealth.com/tls:/etc/hyperledger/fabric/tls
        - peer0.casa.securehealth.com:/var/hyperledger/production
    ports:
      - 9051:7051