version: '2'

volumes:
  orderer.securehealth.com:
  peer0.rabat.securehealth.com:
  peer0.casa.securehealth.com:


networks:
  securehealth_net:

services:

  orderer.securehealth.com:
    extends:
      file:   ./docker-compose-base.yaml
      service: orderer.securehealth.com
    container_name: orderer.securehealth.com
    networks:
      - securehealth_net

  peer0.rabat.securehealth.com:
    container_name: peer0.rabat.securehealth.com
    extends:
      file:  ./docker-compose-base.yaml
      service: peer0.rabat.securehealth.com
    networks:
      - securehealth_net

  
  peer0.casa.securehealth.com:
    container_name: peer0.casa.securehealth.com
    extends:
      file:  ./docker-compose-base.yaml
      service: peer0.casa.securehealth.com
    networks:
      - securehealth_net

 
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    dns_search: .
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.rabat.securehealth.com:7051
      - CORE_PEER_LOCALMSPID=HospitalRabatMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/fabric/config/crypto-config/peerOrganizations/rabat.securehealth.com/peers/peer0.rabat.securehealth.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/fabric/config/crypto-config/peerOrganizations/rabat.securehealth.com/peers/peer0.rabat.securehealth.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/fabric/config/crypto-config/peerOrganizations/casa.securehealth.com/peers/peer0.casa.securehealth.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/fabric/config/crypto-config/peerOrganizations/casa.securehealth.com/users/Admin@casa.securehealth.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/chain
        - ../config/crypto-config:/opt/gopath/fabric/securehealth/crypto-config/
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ../channel-artifacts:/opt/gopath/fabric/channel-artifacts

    depends_on:
      - orderer.securehealth.com
      - peer0.rabat.securehealth.com
      - peer0.casa.securehealth.com
    networks:
      - securehealth_net